version: '2'

services:
  nginx-proxy:
    # siehe: https://hub.docker.com/r/jwilder/nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    #scale: 3
    environment:
      - VIRTUAL_HOST=whoami.local

  whoami2:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami2.local
